// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.example.project_grpc.stubs;

public interface GetAllComptesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllComptesRequest)
    com.google.protobuf.MessageOrBuilder {
}
