// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.example.project_grpc.stubs;

public interface GetCompteByTypeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCompteByTypeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Liste des comptes correspondant au type
   * </pre>
   *
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<com.example.project_grpc.stubs.Compte> 
      getComptesList();
  /**
   * <pre>
   * Liste des comptes correspondant au type
   * </pre>
   *
   * <code>repeated .Compte comptes = 1;</code>
   */
  com.example.project_grpc.stubs.Compte getComptes(int index);
  /**
   * <pre>
   * Liste des comptes correspondant au type
   * </pre>
   *
   * <code>repeated .Compte comptes = 1;</code>
   */
  int getComptesCount();
  /**
   * <pre>
   * Liste des comptes correspondant au type
   * </pre>
   *
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<? extends com.example.project_grpc.stubs.CompteOrBuilder> 
      getComptesOrBuilderList();
  /**
   * <pre>
   * Liste des comptes correspondant au type
   * </pre>
   *
   * <code>repeated .Compte comptes = 1;</code>
   */
  com.example.project_grpc.stubs.CompteOrBuilder getComptesOrBuilder(
      int index);
}
